import { Service } from "repzo/src/types";
type ENV = "staging" | "production" | "local";
type NameSpaces = string[];
export interface Command {
  command: string;
  description: string;
  name: string;
}
export interface FormData {
  repzoApiKey: string;
  suiteTalkUrl: string;
  consumerKey: string;
  consumerSecret: string;
  tokenKey: string;
  tokenSecret: string;
  realm: string;
}
interface AppWithCustomFormData
  extends Service.App.Schema_with_populated_AvailableApp {
  formData: FormData;
}
export interface CommandEvent {
  app: AppWithCustomFormData;
  command: string;
  nameSpace: NameSpaces;
  meta?: any;
  sync_id?: string;
  end_of_day: string;
  timezone: string;
  data?: any;
  env: ENV;
}
export interface Result {
  command?: string;
  netsuite_total: number;
  repzo_total?: number;
  created: number;
  updated: number;
  failed: number;
  migrated_docs: number;
}
export type FailedDocsReport = {
  method: "insert" | "update" | "delete" | "fetchingData";
  doc_id?: string;
  doc?: any;
  error_message: any;
  [key: string]: any;
}[];
export interface SuiteTalkRESTResponse {
  links: any[];
  count: number;
  hasMore: boolean;
  items: any[];
  offset: number;
  totalResults: number;
}
export interface RepzoClientCreateBody {
  name: string;
  email?: string;
  cell_phone?: string;
  phone?: string;
  financials?: {
    credit_limit?: number;
  };
  comment?: string;
  integration_meta: IntegrationMeta;
}
export interface RepzoClient {
  integration_meta: IntegrationMeta;
  _id: string;
}
interface IntegrationMeta {
  id?: string;
  netsuite_id?: string;
  netsuite_last_sync?: string;
}
export interface NetSuiteClient {
  links: any[];
  alcoholrecipienttype: string;
  altname: string;
  balancesearch: string;
  category: string;
  companyname: string;
  creditholdoverride: string;
  creditlimit: string;
  currency: string;
  custentity8: string;
  custentity_aljomaih_customer_type: string;
  custentity_atc_customer_location_: string;
  custentity_edoc_gen_trans_pdf: string;
  custentity_edoc_use_sender_list: string;
  custentity_ksa_credit_memo_pdf_template: string;
  custentity_ksa_customer_schemeid: string;
  custentity_ksa_debit_note_pdf_template: string;
  custentity_ksa_invoice_pdf_template: string;
  custentity_psg_ei_auto_select_temp_sm: string;
  custentity_psg_ei_entity_edoc_standard: string;
  dateclosed: string;
  datecreated: string;
  defaultbillingaddress: string;
  defaultshippingaddress: string;
  duplicate: string;
  emailpreference: string;
  emailtransactions: string;
  entityid: string;
  entitynumber: string;
  entitystatus: string;
  entitytitle: string;
  externalid: string;
  faxtransactions: string;
  firstsaledate: string;
  firstsaleperiod: string;
  fullname: string;
  giveaccess: string;
  id: string;
  isautogeneratedrepresentingentity: string;
  isbudgetapproved: string;
  isinactive: string;
  isjob: string;
  isperson: string;
  language: string;
  lastmodifieddate: string;
  lastsaledate: string;
  lastsaleperiod: string;
  oncredithold: string;
  overduebalancesearch: string;
  printtransactions: string;
  probability: string;
  receivablesaccount: string;
  salesrep: string;
  searchstage: string;
  shipcomplete: string;
  shippingcarrier: string;
  terms: string;
  toplevelparent: string;
  unbilledorderssearch: string;
  weblead: string;
  email: string;
  phone: string;
  comments: string;
}
export {};
